[project]
name = "project-template"
description = "Starting off point for Python projects"
version = "0.0.1"
authors = [
    { name = "Tejas", email = "tejasanilshah@gmail.com" }
]
dependencies = [

]

[project.optional-dependencies]
dev = [
    "pre-commit"
]

[project.scripts]
main = "main:main"
